name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golangci_lint: [v1.45]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: ${{ matrix.golangci_lint }}
          args: --timeout=2m
          only-new-issues: false
          working-directory: .
  build:
    needs: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v cmd/gosign/main.go

      - name: Test
        run: go test -v ./...

      - name: Coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          file: ./coverage.txt
          flags: unittests
          env_vars: OS,GOLANG
          name: codecov-umbrell
          fail_ci_if_error: false
